version: '3.9'

services:
  walletwise-database:
    container_name: walletwise-database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./_apps/walletwise:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=walletwise-database
    networks:
      - walletwise-network

networks:
  walletwise-network:
    driver: bridge
